- name: Import main Common role
  include_role:
    name: common
    tasks_from: main

- name: Install Redis Server
  apt:
    name: redis-server
    state: present
    update_cache: yes

- name: Update Redis config from Local address to 0.0.0.0
  replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    
  notify:
     - restart redis.service

- name: Start Redis
  systemd:
    name: redis
    state: started
    enabled: yes

- name: reload Redis
  systemd:
    name: redis
    state: reloaded
    enabled: yes