- name: Demo on filters
  hosts: all
  vars:
   URL: https://github.com/zs-amrutha/frontend/archive/main.zip
  
  tasks:
    - name: Print filename of url
      debug:
        msg: "{{ URL | urlsplit }}"

    - name: Print last colum
      debug:
        msg: "{{ URL.split'/' }}"        