- name: Demo on loop
  hosts: all
  tasks:
    - name: Print fruitnames
      debug:
        msg: "Fruit = {{ item }}"
      loop:
        - Monday
        - Tuesday
        - Wednesday
        - Thursday