- name: npm Installation 
  apt:
    name: npm
    update_cache: yes
    state: present         

- name: Create todoapp and frontend dir
  file:
    path: /var/www/html/todoapp/frontend
    state: directory      
    
- name: Download frontend Component
  get_url:
    url: http://172.31.68.193:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
    dest: /tmp/frontend.zip
    username: admin
    password: admin123

- name: Unzip frontend Component
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html/todoapp/frontend
    remote_src: yes  

- name: Copy index.js file
  template:
    src: index.js
    dest: /var/www/html/todoapp/frontend/config/index.js  

- name: NPM start 
  command: npm start
  args:
    chdir: /var/www/html/todoapp/frontend
  async: 42
  poll: 0
  become: yes
  become_user: root              

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node_exporter