- name: npm Installation 
  apt:
    name: npm
    update_cache: yes
    state: present   

- name: Add user todoapp
  user:
    name: todoapp
    shell: /bin/bash

- name: Download {{COMPONENT}} from nexus
  get_url:
    url: http://172.31.68.193:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp/{{COMPONENT}}.zip
    username: admin
    password: admin123

- name: Unzip {{COMPONENT}} Component
  unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /home/todoapp/{{COMPONENT}}
    remote_src: yes  

- name: Copy systemd file
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} Service
  systemd:
    name: "{{COMPONENT}}"
    daemon_reload: yes
    state: started
    enabled: yes  

- name: Install Node Exporter Prometheus Monitoring
  include_role:
    name: common
    tasks_from: node_exporter 

# - name: Install Filebeat Monitoring
#   include_role:
#     name: common
#     tasks_from: filebeat
#   vars:
#     IS_STRUCTURED: false
#     LOG_FILES:
#       - { file: "/var/log/"{{COMPONENT}}".log", type: "{{COMPONENT}}" }     

  






























     




# - name: Install Filebeat Monitoring
#   include_role:
#     name: common
#     tasks_from: filebeat
#   vars:
#     IS_STRUCTURED: false
#     LOG_FILES:
#       - { file: "/var/log/nginx/access.log", type: "nginx_access" }

# - name: NPM start 
#   command: npm start
#   args:
#     chdir: /var/www/html/todoapp/frontend
#   async: 42
#   poll: 0
#   become: yes
#   become_user: root       