    - name: NGINX Installation 
      apt:
        name: nginx
        update_cache: yes
        state: present

    - name: Start Nginx
      systemd:
       name: nginx
       enabled: yes

    - name: npm Installation 
      apt:
        name: npm
        update_cache: yes
        state: present   
        
    # - name: Add user todoapp
    #   user:
    #     name: todoapp
    #     shell: /bin/bash
    - name: Create dir
      file:
       path: /var/www/html/todoapp 
       state: directory      
    
    - name: Download frontend Component
      get_url:
        url: http://100.26.172.235:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
        dest: /tmp/frontend.zip
        username: admin
        password: admin123

    - name: Unzip frontend Component
      unarchive:
        src: /tmp/frontend.zip
        dest: /var/www/html/todoapp
        remote_src: yes

    - name: Replace before the expression till the begin of the file (requires Ansible >= 2.4)
      replace:
        path: /etc/nginx/sites-available/default
        before: root /var/www/html;
        regexp: root /var/www/html;
        replace: root /var/www/html/todoapp/frontend/dist;        

    - name: Use NPM to start the target
      command: npm start
      args:
        chdir: /var/www/html/todoapp/frontend
      async: 42
      poll: 0
      become: yes
      become_user: root

    # - name: Use NPM to start the target
    #   command: npm start
    #   path: /var/www/html/todoapp/frontend
    #   become: yes
    #   become_user: root