- name: npm Installation 
  apt:
    name: npm
    update_cache: yes
    state: present         

- name: Create todoapp and frontend dir
  file:
    path: /var/www/html/todoapp/frontend
    state: directory      
    
- name: Download frontend from nexus
  get_url:
    url: http://172.31.68.193:8081/repository/frontend/frontend-{{APP_VERSION}}.zip
    dest: /tmp/frontend.zip
    username: admin
    password: admin123

- name: Unzip frontend Component
  unarchive:
    src: /tmp/frontend.zip
    dest: /var/www/html/todoapp/frontend
    remote_src: yes  

- name: Copy systemd file
  template:
    src: systemd.service
    dest: /etc/systemd/system/frontend.service

- name: Start frontend Service
  systemd:
    name: "frontend"
    daemon_reload: yes
    state: started
    enabled: yes    




























# - name: Install Filebeat Monitoring
#   include_role:
#     name: common
#     tasks_from: filebeat
#   vars:
#     IS_STRUCTURED: false
#     LOG_FILES:
#       - { file: "/var/log/frontend.log", type: "frontend" } 

# - name: Install Node Exporter Prometheus Monitoring
#   include_role:
#     name: common
#     tasks_from: node_exporter      

# - name: Copy index.js file
#   template:
#     src: index.js
#     dest: /var/www/html/todoapp/frontend/config/index.js

# - name: Install Filebeat Monitoring
#   include_role:
#     name: common
#     tasks_from: filebeat
#   vars:
#     IS_STRUCTURED: false
#     LOG_FILES:
#       - { file: "/var/log/nginx/access.log", type: "nginx_access" }

# - name: NPM start 
#   command: npm start
#   args:
#     chdir: /var/www/html/todoapp/frontend
#   async: 42
#   poll: 0
#   become: yes
#   become_user: root       