    - name: Install the version '1.8.0' of package "java"
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes
      become : true    
    
    - name: Maven Installation 
      apt:
        name: maven
        update_cache: yes
        state: present