    - name: Copy {{COMPONENT}} systemd service file
      template:
        src: systemd.service
        dest: /etc/systemd/system/{{COMPONENT}}.service             

    - name: Restart {{COMPONENT}} Service
      systemd:
        name: "{{COMPONENT}}"
        daemon_reload: yes
        state: restarted
        enabled: yes